
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Topic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Topic
 * 
 */
export type TopicModel = runtime.Types.Result.DefaultSelection<Prisma.$TopicPayload>

export type AggregateTopic = {
  _count: TopicCountAggregateOutputType | null
  _avg: TopicAvgAggregateOutputType | null
  _sum: TopicSumAggregateOutputType | null
  _min: TopicMinAggregateOutputType | null
  _max: TopicMaxAggregateOutputType | null
}

export type TopicAvgAggregateOutputType = {
  id: number | null
  createdBy: number | null
  updatedBy: number | null
}

export type TopicSumAggregateOutputType = {
  id: number | null
  createdBy: number | null
  updatedBy: number | null
}

export type TopicMinAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  createdBy: number | null
  updatedBy: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TopicMaxAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  createdBy: number | null
  updatedBy: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TopicCountAggregateOutputType = {
  id: number
  title: number
  description: number
  createdBy: number
  updatedBy: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TopicAvgAggregateInputType = {
  id?: true
  createdBy?: true
  updatedBy?: true
}

export type TopicSumAggregateInputType = {
  id?: true
  createdBy?: true
  updatedBy?: true
}

export type TopicMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdBy?: true
  updatedBy?: true
  createdAt?: true
  updatedAt?: true
}

export type TopicMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdBy?: true
  updatedBy?: true
  createdAt?: true
  updatedAt?: true
}

export type TopicCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdBy?: true
  updatedBy?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TopicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Topic to aggregate.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Topics
  **/
  _count?: true | TopicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TopicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TopicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TopicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TopicMaxAggregateInputType
}

export type GetTopicAggregateType<T extends TopicAggregateArgs> = {
      [P in keyof T & keyof AggregateTopic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTopic[P]>
    : Prisma.GetScalarType<T[P], AggregateTopic[P]>
}




export type TopicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopicWhereInput
  orderBy?: Prisma.TopicOrderByWithAggregationInput | Prisma.TopicOrderByWithAggregationInput[]
  by: Prisma.TopicScalarFieldEnum[] | Prisma.TopicScalarFieldEnum
  having?: Prisma.TopicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TopicCountAggregateInputType | true
  _avg?: TopicAvgAggregateInputType
  _sum?: TopicSumAggregateInputType
  _min?: TopicMinAggregateInputType
  _max?: TopicMaxAggregateInputType
}

export type TopicGroupByOutputType = {
  id: number
  title: string
  description: string
  createdBy: number
  updatedBy: number | null
  createdAt: Date
  updatedAt: Date
  _count: TopicCountAggregateOutputType | null
  _avg: TopicAvgAggregateOutputType | null
  _sum: TopicSumAggregateOutputType | null
  _min: TopicMinAggregateOutputType | null
  _max: TopicMaxAggregateOutputType | null
}

export type GetTopicGroupByPayload<T extends TopicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TopicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TopicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TopicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TopicGroupByOutputType[P]>
      }
    >
  >



export type TopicWhereInput = {
  AND?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  OR?: Prisma.TopicWhereInput[]
  NOT?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  id?: Prisma.IntFilter<"Topic"> | number
  title?: Prisma.StringFilter<"Topic"> | string
  description?: Prisma.StringFilter<"Topic"> | string
  createdBy?: Prisma.IntFilter<"Topic"> | number
  updatedBy?: Prisma.IntNullableFilter<"Topic"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  createdUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  updatedUser?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  materials?: Prisma.MaterialListRelationFilter
  assignment?: Prisma.AssignmentListRelationFilter
}

export type TopicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdUser?: Prisma.UserOrderByWithRelationInput
  updatedUser?: Prisma.UserOrderByWithRelationInput
  materials?: Prisma.MaterialOrderByRelationAggregateInput
  assignment?: Prisma.AssignmentOrderByRelationAggregateInput
}

export type TopicWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  OR?: Prisma.TopicWhereInput[]
  NOT?: Prisma.TopicWhereInput | Prisma.TopicWhereInput[]
  title?: Prisma.StringFilter<"Topic"> | string
  description?: Prisma.StringFilter<"Topic"> | string
  createdBy?: Prisma.IntFilter<"Topic"> | number
  updatedBy?: Prisma.IntNullableFilter<"Topic"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  createdUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  updatedUser?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  materials?: Prisma.MaterialListRelationFilter
  assignment?: Prisma.AssignmentListRelationFilter
}, "id">

export type TopicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TopicCountOrderByAggregateInput
  _avg?: Prisma.TopicAvgOrderByAggregateInput
  _max?: Prisma.TopicMaxOrderByAggregateInput
  _min?: Prisma.TopicMinOrderByAggregateInput
  _sum?: Prisma.TopicSumOrderByAggregateInput
}

export type TopicScalarWhereWithAggregatesInput = {
  AND?: Prisma.TopicScalarWhereWithAggregatesInput | Prisma.TopicScalarWhereWithAggregatesInput[]
  OR?: Prisma.TopicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TopicScalarWhereWithAggregatesInput | Prisma.TopicScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Topic"> | number
  title?: Prisma.StringWithAggregatesFilter<"Topic"> | string
  description?: Prisma.StringWithAggregatesFilter<"Topic"> | string
  createdBy?: Prisma.IntWithAggregatesFilter<"Topic"> | number
  updatedBy?: Prisma.IntNullableWithAggregatesFilter<"Topic"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Topic"> | Date | string
}

export type TopicCreateInput = {
  title: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  createdUser: Prisma.UserCreateNestedOneWithoutTopicsCreatedInput
  updatedUser?: Prisma.UserCreateNestedOneWithoutTopicsUpdatedInput
  materials?: Prisma.MaterialCreateNestedManyWithoutTopicInput
  assignment?: Prisma.AssignmentCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateInput = {
  id?: number
  title: string
  description: string
  createdBy: number
  updatedBy?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  materials?: Prisma.MaterialUncheckedCreateNestedManyWithoutTopicInput
  assignment?: Prisma.AssignmentUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdUser?: Prisma.UserUpdateOneRequiredWithoutTopicsCreatedNestedInput
  updatedUser?: Prisma.UserUpdateOneWithoutTopicsUpdatedNestedInput
  materials?: Prisma.MaterialUpdateManyWithoutTopicNestedInput
  assignment?: Prisma.AssignmentUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdBy?: Prisma.IntFieldUpdateOperationsInput | number
  updatedBy?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  materials?: Prisma.MaterialUncheckedUpdateManyWithoutTopicNestedInput
  assignment?: Prisma.AssignmentUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateManyInput = {
  id?: number
  title: string
  description: string
  createdBy: number
  updatedBy?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TopicUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TopicUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdBy?: Prisma.IntFieldUpdateOperationsInput | number
  updatedBy?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TopicListRelationFilter = {
  every?: Prisma.TopicWhereInput
  some?: Prisma.TopicWhereInput
  none?: Prisma.TopicWhereInput
}

export type TopicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TopicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TopicAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type TopicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TopicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TopicSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type TopicScalarRelationFilter = {
  is?: Prisma.TopicWhereInput
  isNot?: Prisma.TopicWhereInput
}

export type TopicCreateNestedManyWithoutCreatedUserInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutCreatedUserInput, Prisma.TopicUncheckedCreateWithoutCreatedUserInput> | Prisma.TopicCreateWithoutCreatedUserInput[] | Prisma.TopicUncheckedCreateWithoutCreatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutCreatedUserInput | Prisma.TopicCreateOrConnectWithoutCreatedUserInput[]
  createMany?: Prisma.TopicCreateManyCreatedUserInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicCreateNestedManyWithoutUpdatedUserInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutUpdatedUserInput, Prisma.TopicUncheckedCreateWithoutUpdatedUserInput> | Prisma.TopicCreateWithoutUpdatedUserInput[] | Prisma.TopicUncheckedCreateWithoutUpdatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutUpdatedUserInput | Prisma.TopicCreateOrConnectWithoutUpdatedUserInput[]
  createMany?: Prisma.TopicCreateManyUpdatedUserInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUncheckedCreateNestedManyWithoutCreatedUserInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutCreatedUserInput, Prisma.TopicUncheckedCreateWithoutCreatedUserInput> | Prisma.TopicCreateWithoutCreatedUserInput[] | Prisma.TopicUncheckedCreateWithoutCreatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutCreatedUserInput | Prisma.TopicCreateOrConnectWithoutCreatedUserInput[]
  createMany?: Prisma.TopicCreateManyCreatedUserInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUncheckedCreateNestedManyWithoutUpdatedUserInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutUpdatedUserInput, Prisma.TopicUncheckedCreateWithoutUpdatedUserInput> | Prisma.TopicCreateWithoutUpdatedUserInput[] | Prisma.TopicUncheckedCreateWithoutUpdatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutUpdatedUserInput | Prisma.TopicCreateOrConnectWithoutUpdatedUserInput[]
  createMany?: Prisma.TopicCreateManyUpdatedUserInputEnvelope
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
}

export type TopicUpdateManyWithoutCreatedUserNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutCreatedUserInput, Prisma.TopicUncheckedCreateWithoutCreatedUserInput> | Prisma.TopicCreateWithoutCreatedUserInput[] | Prisma.TopicUncheckedCreateWithoutCreatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutCreatedUserInput | Prisma.TopicCreateOrConnectWithoutCreatedUserInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutCreatedUserInput | Prisma.TopicUpsertWithWhereUniqueWithoutCreatedUserInput[]
  createMany?: Prisma.TopicCreateManyCreatedUserInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutCreatedUserInput | Prisma.TopicUpdateWithWhereUniqueWithoutCreatedUserInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutCreatedUserInput | Prisma.TopicUpdateManyWithWhereWithoutCreatedUserInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicUpdateManyWithoutUpdatedUserNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutUpdatedUserInput, Prisma.TopicUncheckedCreateWithoutUpdatedUserInput> | Prisma.TopicCreateWithoutUpdatedUserInput[] | Prisma.TopicUncheckedCreateWithoutUpdatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutUpdatedUserInput | Prisma.TopicCreateOrConnectWithoutUpdatedUserInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutUpdatedUserInput | Prisma.TopicUpsertWithWhereUniqueWithoutUpdatedUserInput[]
  createMany?: Prisma.TopicCreateManyUpdatedUserInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutUpdatedUserInput | Prisma.TopicUpdateWithWhereUniqueWithoutUpdatedUserInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutUpdatedUserInput | Prisma.TopicUpdateManyWithWhereWithoutUpdatedUserInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicUncheckedUpdateManyWithoutCreatedUserNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutCreatedUserInput, Prisma.TopicUncheckedCreateWithoutCreatedUserInput> | Prisma.TopicCreateWithoutCreatedUserInput[] | Prisma.TopicUncheckedCreateWithoutCreatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutCreatedUserInput | Prisma.TopicCreateOrConnectWithoutCreatedUserInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutCreatedUserInput | Prisma.TopicUpsertWithWhereUniqueWithoutCreatedUserInput[]
  createMany?: Prisma.TopicCreateManyCreatedUserInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutCreatedUserInput | Prisma.TopicUpdateWithWhereUniqueWithoutCreatedUserInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutCreatedUserInput | Prisma.TopicUpdateManyWithWhereWithoutCreatedUserInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type TopicUncheckedUpdateManyWithoutUpdatedUserNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutUpdatedUserInput, Prisma.TopicUncheckedCreateWithoutUpdatedUserInput> | Prisma.TopicCreateWithoutUpdatedUserInput[] | Prisma.TopicUncheckedCreateWithoutUpdatedUserInput[]
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutUpdatedUserInput | Prisma.TopicCreateOrConnectWithoutUpdatedUserInput[]
  upsert?: Prisma.TopicUpsertWithWhereUniqueWithoutUpdatedUserInput | Prisma.TopicUpsertWithWhereUniqueWithoutUpdatedUserInput[]
  createMany?: Prisma.TopicCreateManyUpdatedUserInputEnvelope
  set?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  disconnect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  delete?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  connect?: Prisma.TopicWhereUniqueInput | Prisma.TopicWhereUniqueInput[]
  update?: Prisma.TopicUpdateWithWhereUniqueWithoutUpdatedUserInput | Prisma.TopicUpdateWithWhereUniqueWithoutUpdatedUserInput[]
  updateMany?: Prisma.TopicUpdateManyWithWhereWithoutUpdatedUserInput | Prisma.TopicUpdateManyWithWhereWithoutUpdatedUserInput[]
  deleteMany?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TopicCreateNestedOneWithoutMaterialsInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutMaterialsInput, Prisma.TopicUncheckedCreateWithoutMaterialsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutMaterialsInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUpdateOneRequiredWithoutMaterialsNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutMaterialsInput, Prisma.TopicUncheckedCreateWithoutMaterialsInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutMaterialsInput
  upsert?: Prisma.TopicUpsertWithoutMaterialsInput
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutMaterialsInput, Prisma.TopicUpdateWithoutMaterialsInput>, Prisma.TopicUncheckedUpdateWithoutMaterialsInput>
}

export type TopicCreateNestedOneWithoutAssignmentInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutAssignmentInput, Prisma.TopicUncheckedCreateWithoutAssignmentInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutAssignmentInput
  connect?: Prisma.TopicWhereUniqueInput
}

export type TopicUpdateOneRequiredWithoutAssignmentNestedInput = {
  create?: Prisma.XOR<Prisma.TopicCreateWithoutAssignmentInput, Prisma.TopicUncheckedCreateWithoutAssignmentInput>
  connectOrCreate?: Prisma.TopicCreateOrConnectWithoutAssignmentInput
  upsert?: Prisma.TopicUpsertWithoutAssignmentInput
  connect?: Prisma.TopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TopicUpdateToOneWithWhereWithoutAssignmentInput, Prisma.TopicUpdateWithoutAssignmentInput>, Prisma.TopicUncheckedUpdateWithoutAssignmentInput>
}

export type TopicCreateWithoutCreatedUserInput = {
  title: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  updatedUser?: Prisma.UserCreateNestedOneWithoutTopicsUpdatedInput
  materials?: Prisma.MaterialCreateNestedManyWithoutTopicInput
  assignment?: Prisma.AssignmentCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutCreatedUserInput = {
  id?: number
  title: string
  description: string
  updatedBy?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  materials?: Prisma.MaterialUncheckedCreateNestedManyWithoutTopicInput
  assignment?: Prisma.AssignmentUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutCreatedUserInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutCreatedUserInput, Prisma.TopicUncheckedCreateWithoutCreatedUserInput>
}

export type TopicCreateManyCreatedUserInputEnvelope = {
  data: Prisma.TopicCreateManyCreatedUserInput | Prisma.TopicCreateManyCreatedUserInput[]
  skipDuplicates?: boolean
}

export type TopicCreateWithoutUpdatedUserInput = {
  title: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  createdUser: Prisma.UserCreateNestedOneWithoutTopicsCreatedInput
  materials?: Prisma.MaterialCreateNestedManyWithoutTopicInput
  assignment?: Prisma.AssignmentCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutUpdatedUserInput = {
  id?: number
  title: string
  description: string
  createdBy: number
  createdAt?: Date | string
  updatedAt?: Date | string
  materials?: Prisma.MaterialUncheckedCreateNestedManyWithoutTopicInput
  assignment?: Prisma.AssignmentUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutUpdatedUserInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutUpdatedUserInput, Prisma.TopicUncheckedCreateWithoutUpdatedUserInput>
}

export type TopicCreateManyUpdatedUserInputEnvelope = {
  data: Prisma.TopicCreateManyUpdatedUserInput | Prisma.TopicCreateManyUpdatedUserInput[]
  skipDuplicates?: boolean
}

export type TopicUpsertWithWhereUniqueWithoutCreatedUserInput = {
  where: Prisma.TopicWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicUpdateWithoutCreatedUserInput, Prisma.TopicUncheckedUpdateWithoutCreatedUserInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutCreatedUserInput, Prisma.TopicUncheckedCreateWithoutCreatedUserInput>
}

export type TopicUpdateWithWhereUniqueWithoutCreatedUserInput = {
  where: Prisma.TopicWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutCreatedUserInput, Prisma.TopicUncheckedUpdateWithoutCreatedUserInput>
}

export type TopicUpdateManyWithWhereWithoutCreatedUserInput = {
  where: Prisma.TopicScalarWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyWithoutCreatedUserInput>
}

export type TopicScalarWhereInput = {
  AND?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
  OR?: Prisma.TopicScalarWhereInput[]
  NOT?: Prisma.TopicScalarWhereInput | Prisma.TopicScalarWhereInput[]
  id?: Prisma.IntFilter<"Topic"> | number
  title?: Prisma.StringFilter<"Topic"> | string
  description?: Prisma.StringFilter<"Topic"> | string
  createdBy?: Prisma.IntFilter<"Topic"> | number
  updatedBy?: Prisma.IntNullableFilter<"Topic"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Topic"> | Date | string
}

export type TopicUpsertWithWhereUniqueWithoutUpdatedUserInput = {
  where: Prisma.TopicWhereUniqueInput
  update: Prisma.XOR<Prisma.TopicUpdateWithoutUpdatedUserInput, Prisma.TopicUncheckedUpdateWithoutUpdatedUserInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutUpdatedUserInput, Prisma.TopicUncheckedCreateWithoutUpdatedUserInput>
}

export type TopicUpdateWithWhereUniqueWithoutUpdatedUserInput = {
  where: Prisma.TopicWhereUniqueInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutUpdatedUserInput, Prisma.TopicUncheckedUpdateWithoutUpdatedUserInput>
}

export type TopicUpdateManyWithWhereWithoutUpdatedUserInput = {
  where: Prisma.TopicScalarWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyWithoutUpdatedUserInput>
}

export type TopicCreateWithoutMaterialsInput = {
  title: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  createdUser: Prisma.UserCreateNestedOneWithoutTopicsCreatedInput
  updatedUser?: Prisma.UserCreateNestedOneWithoutTopicsUpdatedInput
  assignment?: Prisma.AssignmentCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutMaterialsInput = {
  id?: number
  title: string
  description: string
  createdBy: number
  updatedBy?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assignment?: Prisma.AssignmentUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutMaterialsInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutMaterialsInput, Prisma.TopicUncheckedCreateWithoutMaterialsInput>
}

export type TopicUpsertWithoutMaterialsInput = {
  update: Prisma.XOR<Prisma.TopicUpdateWithoutMaterialsInput, Prisma.TopicUncheckedUpdateWithoutMaterialsInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutMaterialsInput, Prisma.TopicUncheckedCreateWithoutMaterialsInput>
  where?: Prisma.TopicWhereInput
}

export type TopicUpdateToOneWithWhereWithoutMaterialsInput = {
  where?: Prisma.TopicWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutMaterialsInput, Prisma.TopicUncheckedUpdateWithoutMaterialsInput>
}

export type TopicUpdateWithoutMaterialsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdUser?: Prisma.UserUpdateOneRequiredWithoutTopicsCreatedNestedInput
  updatedUser?: Prisma.UserUpdateOneWithoutTopicsUpdatedNestedInput
  assignment?: Prisma.AssignmentUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutMaterialsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdBy?: Prisma.IntFieldUpdateOperationsInput | number
  updatedBy?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignment?: Prisma.AssignmentUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateWithoutAssignmentInput = {
  title: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  createdUser: Prisma.UserCreateNestedOneWithoutTopicsCreatedInput
  updatedUser?: Prisma.UserCreateNestedOneWithoutTopicsUpdatedInput
  materials?: Prisma.MaterialCreateNestedManyWithoutTopicInput
}

export type TopicUncheckedCreateWithoutAssignmentInput = {
  id?: number
  title: string
  description: string
  createdBy: number
  updatedBy?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  materials?: Prisma.MaterialUncheckedCreateNestedManyWithoutTopicInput
}

export type TopicCreateOrConnectWithoutAssignmentInput = {
  where: Prisma.TopicWhereUniqueInput
  create: Prisma.XOR<Prisma.TopicCreateWithoutAssignmentInput, Prisma.TopicUncheckedCreateWithoutAssignmentInput>
}

export type TopicUpsertWithoutAssignmentInput = {
  update: Prisma.XOR<Prisma.TopicUpdateWithoutAssignmentInput, Prisma.TopicUncheckedUpdateWithoutAssignmentInput>
  create: Prisma.XOR<Prisma.TopicCreateWithoutAssignmentInput, Prisma.TopicUncheckedCreateWithoutAssignmentInput>
  where?: Prisma.TopicWhereInput
}

export type TopicUpdateToOneWithWhereWithoutAssignmentInput = {
  where?: Prisma.TopicWhereInput
  data: Prisma.XOR<Prisma.TopicUpdateWithoutAssignmentInput, Prisma.TopicUncheckedUpdateWithoutAssignmentInput>
}

export type TopicUpdateWithoutAssignmentInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdUser?: Prisma.UserUpdateOneRequiredWithoutTopicsCreatedNestedInput
  updatedUser?: Prisma.UserUpdateOneWithoutTopicsUpdatedNestedInput
  materials?: Prisma.MaterialUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutAssignmentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdBy?: Prisma.IntFieldUpdateOperationsInput | number
  updatedBy?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  materials?: Prisma.MaterialUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicCreateManyCreatedUserInput = {
  id?: number
  title: string
  description: string
  updatedBy?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TopicCreateManyUpdatedUserInput = {
  id?: number
  title: string
  description: string
  createdBy: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TopicUpdateWithoutCreatedUserInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedUser?: Prisma.UserUpdateOneWithoutTopicsUpdatedNestedInput
  materials?: Prisma.MaterialUpdateManyWithoutTopicNestedInput
  assignment?: Prisma.AssignmentUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutCreatedUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  updatedBy?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  materials?: Prisma.MaterialUncheckedUpdateManyWithoutTopicNestedInput
  assignment?: Prisma.AssignmentUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateManyWithoutCreatedUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  updatedBy?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TopicUpdateWithoutUpdatedUserInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdUser?: Prisma.UserUpdateOneRequiredWithoutTopicsCreatedNestedInput
  materials?: Prisma.MaterialUpdateManyWithoutTopicNestedInput
  assignment?: Prisma.AssignmentUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateWithoutUpdatedUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdBy?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  materials?: Prisma.MaterialUncheckedUpdateManyWithoutTopicNestedInput
  assignment?: Prisma.AssignmentUncheckedUpdateManyWithoutTopicNestedInput
}

export type TopicUncheckedUpdateManyWithoutUpdatedUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdBy?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TopicCountOutputType
 */

export type TopicCountOutputType = {
  materials: number
  assignment: number
}

export type TopicCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  materials?: boolean | TopicCountOutputTypeCountMaterialsArgs
  assignment?: boolean | TopicCountOutputTypeCountAssignmentArgs
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicCountOutputType
   */
  select?: Prisma.TopicCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeCountMaterialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaterialWhereInput
}

/**
 * TopicCountOutputType without action
 */
export type TopicCountOutputTypeCountAssignmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssignmentWhereInput
}


export type TopicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdBy?: boolean
  updatedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedUser?: boolean | Prisma.Topic$updatedUserArgs<ExtArgs>
  materials?: boolean | Prisma.Topic$materialsArgs<ExtArgs>
  assignment?: boolean | Prisma.Topic$assignmentArgs<ExtArgs>
  _count?: boolean | Prisma.TopicCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topic"]>

export type TopicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdBy?: boolean
  updatedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedUser?: boolean | Prisma.Topic$updatedUserArgs<ExtArgs>
}, ExtArgs["result"]["topic"]>

export type TopicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdBy?: boolean
  updatedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedUser?: boolean | Prisma.Topic$updatedUserArgs<ExtArgs>
}, ExtArgs["result"]["topic"]>

export type TopicSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  createdBy?: boolean
  updatedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TopicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "createdBy" | "updatedBy" | "createdAt" | "updatedAt", ExtArgs["result"]["topic"]>
export type TopicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedUser?: boolean | Prisma.Topic$updatedUserArgs<ExtArgs>
  materials?: boolean | Prisma.Topic$materialsArgs<ExtArgs>
  assignment?: boolean | Prisma.Topic$assignmentArgs<ExtArgs>
  _count?: boolean | Prisma.TopicCountOutputTypeDefaultArgs<ExtArgs>
}
export type TopicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedUser?: boolean | Prisma.Topic$updatedUserArgs<ExtArgs>
}
export type TopicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedUser?: boolean | Prisma.Topic$updatedUserArgs<ExtArgs>
}

export type $TopicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Topic"
  objects: {
    createdUser: Prisma.$UserPayload<ExtArgs>
    updatedUser: Prisma.$UserPayload<ExtArgs> | null
    materials: Prisma.$MaterialPayload<ExtArgs>[]
    assignment: Prisma.$AssignmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    description: string
    createdBy: number
    updatedBy: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["topic"]>
  composites: {}
}

export type TopicGetPayload<S extends boolean | null | undefined | TopicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TopicPayload, S>

export type TopicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TopicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TopicCountAggregateInputType | true
  }

export interface TopicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Topic'], meta: { name: 'Topic' } }
  /**
   * Find zero or one Topic that matches the filter.
   * @param {TopicFindUniqueArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TopicFindUniqueArgs>(args: Prisma.SelectSubset<T, TopicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Topic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TopicFindUniqueOrThrowArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TopicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TopicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Topic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicFindFirstArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TopicFindFirstArgs>(args?: Prisma.SelectSubset<T, TopicFindFirstArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Topic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicFindFirstOrThrowArgs} args - Arguments to find a Topic
   * @example
   * // Get one Topic
   * const topic = await prisma.topic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TopicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TopicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Topics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Topics
   * const topics = await prisma.topic.findMany()
   * 
   * // Get first 10 Topics
   * const topics = await prisma.topic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const topicWithIdOnly = await prisma.topic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TopicFindManyArgs>(args?: Prisma.SelectSubset<T, TopicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Topic.
   * @param {TopicCreateArgs} args - Arguments to create a Topic.
   * @example
   * // Create one Topic
   * const Topic = await prisma.topic.create({
   *   data: {
   *     // ... data to create a Topic
   *   }
   * })
   * 
   */
  create<T extends TopicCreateArgs>(args: Prisma.SelectSubset<T, TopicCreateArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Topics.
   * @param {TopicCreateManyArgs} args - Arguments to create many Topics.
   * @example
   * // Create many Topics
   * const topic = await prisma.topic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TopicCreateManyArgs>(args?: Prisma.SelectSubset<T, TopicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Topics and returns the data saved in the database.
   * @param {TopicCreateManyAndReturnArgs} args - Arguments to create many Topics.
   * @example
   * // Create many Topics
   * const topic = await prisma.topic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Topics and only return the `id`
   * const topicWithIdOnly = await prisma.topic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TopicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TopicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Topic.
   * @param {TopicDeleteArgs} args - Arguments to delete one Topic.
   * @example
   * // Delete one Topic
   * const Topic = await prisma.topic.delete({
   *   where: {
   *     // ... filter to delete one Topic
   *   }
   * })
   * 
   */
  delete<T extends TopicDeleteArgs>(args: Prisma.SelectSubset<T, TopicDeleteArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Topic.
   * @param {TopicUpdateArgs} args - Arguments to update one Topic.
   * @example
   * // Update one Topic
   * const topic = await prisma.topic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TopicUpdateArgs>(args: Prisma.SelectSubset<T, TopicUpdateArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Topics.
   * @param {TopicDeleteManyArgs} args - Arguments to filter Topics to delete.
   * @example
   * // Delete a few Topics
   * const { count } = await prisma.topic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TopicDeleteManyArgs>(args?: Prisma.SelectSubset<T, TopicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Topics
   * const topic = await prisma.topic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TopicUpdateManyArgs>(args: Prisma.SelectSubset<T, TopicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Topics and returns the data updated in the database.
   * @param {TopicUpdateManyAndReturnArgs} args - Arguments to update many Topics.
   * @example
   * // Update many Topics
   * const topic = await prisma.topic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Topics and only return the `id`
   * const topicWithIdOnly = await prisma.topic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TopicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TopicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Topic.
   * @param {TopicUpsertArgs} args - Arguments to update or create a Topic.
   * @example
   * // Update or create a Topic
   * const topic = await prisma.topic.upsert({
   *   create: {
   *     // ... data to create a Topic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Topic we want to update
   *   }
   * })
   */
  upsert<T extends TopicUpsertArgs>(args: Prisma.SelectSubset<T, TopicUpsertArgs<ExtArgs>>): Prisma.Prisma__TopicClient<runtime.Types.Result.GetResult<Prisma.$TopicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicCountArgs} args - Arguments to filter Topics to count.
   * @example
   * // Count the number of Topics
   * const count = await prisma.topic.count({
   *   where: {
   *     // ... the filter for the Topics we want to count
   *   }
   * })
  **/
  count<T extends TopicCountArgs>(
    args?: Prisma.Subset<T, TopicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TopicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Topic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TopicAggregateArgs>(args: Prisma.Subset<T, TopicAggregateArgs>): Prisma.PrismaPromise<GetTopicAggregateType<T>>

  /**
   * Group by Topic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TopicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TopicGroupByArgs['orderBy'] }
      : { orderBy?: TopicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TopicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTopicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Topic model
 */
readonly fields: TopicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Topic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TopicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  updatedUser<T extends Prisma.Topic$updatedUserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$updatedUserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  materials<T extends Prisma.Topic$materialsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$materialsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assignment<T extends Prisma.Topic$assignmentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Topic$assignmentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssignmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Topic model
 */
export interface TopicFieldRefs {
  readonly id: Prisma.FieldRef<"Topic", 'Int'>
  readonly title: Prisma.FieldRef<"Topic", 'String'>
  readonly description: Prisma.FieldRef<"Topic", 'String'>
  readonly createdBy: Prisma.FieldRef<"Topic", 'Int'>
  readonly updatedBy: Prisma.FieldRef<"Topic", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Topic", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Topic", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Topic findUnique
 */
export type TopicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic findUniqueOrThrow
 */
export type TopicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic findFirst
 */
export type TopicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Topics.
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Topics.
   */
  distinct?: Prisma.TopicScalarFieldEnum | Prisma.TopicScalarFieldEnum[]
}

/**
 * Topic findFirstOrThrow
 */
export type TopicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topic to fetch.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Topics.
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Topics.
   */
  distinct?: Prisma.TopicScalarFieldEnum | Prisma.TopicScalarFieldEnum[]
}

/**
 * Topic findMany
 */
export type TopicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter, which Topics to fetch.
   */
  where?: Prisma.TopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Topics to fetch.
   */
  orderBy?: Prisma.TopicOrderByWithRelationInput | Prisma.TopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Topics.
   */
  cursor?: Prisma.TopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Topics.
   */
  distinct?: Prisma.TopicScalarFieldEnum | Prisma.TopicScalarFieldEnum[]
}

/**
 * Topic create
 */
export type TopicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * The data needed to create a Topic.
   */
  data: Prisma.XOR<Prisma.TopicCreateInput, Prisma.TopicUncheckedCreateInput>
}

/**
 * Topic createMany
 */
export type TopicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Topics.
   */
  data: Prisma.TopicCreateManyInput | Prisma.TopicCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Topic createManyAndReturn
 */
export type TopicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * The data used to create many Topics.
   */
  data: Prisma.TopicCreateManyInput | Prisma.TopicCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Topic update
 */
export type TopicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * The data needed to update a Topic.
   */
  data: Prisma.XOR<Prisma.TopicUpdateInput, Prisma.TopicUncheckedUpdateInput>
  /**
   * Choose, which Topic to update.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic updateMany
 */
export type TopicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Topics.
   */
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyInput>
  /**
   * Filter which Topics to update
   */
  where?: Prisma.TopicWhereInput
  /**
   * Limit how many Topics to update.
   */
  limit?: number
}

/**
 * Topic updateManyAndReturn
 */
export type TopicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * The data used to update Topics.
   */
  data: Prisma.XOR<Prisma.TopicUpdateManyMutationInput, Prisma.TopicUncheckedUpdateManyInput>
  /**
   * Filter which Topics to update
   */
  where?: Prisma.TopicWhereInput
  /**
   * Limit how many Topics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Topic upsert
 */
export type TopicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * The filter to search for the Topic to update in case it exists.
   */
  where: Prisma.TopicWhereUniqueInput
  /**
   * In case the Topic found by the `where` argument doesn't exist, create a new Topic with this data.
   */
  create: Prisma.XOR<Prisma.TopicCreateInput, Prisma.TopicUncheckedCreateInput>
  /**
   * In case the Topic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TopicUpdateInput, Prisma.TopicUncheckedUpdateInput>
}

/**
 * Topic delete
 */
export type TopicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
  /**
   * Filter which Topic to delete.
   */
  where: Prisma.TopicWhereUniqueInput
}

/**
 * Topic deleteMany
 */
export type TopicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Topics to delete
   */
  where?: Prisma.TopicWhereInput
  /**
   * Limit how many Topics to delete.
   */
  limit?: number
}

/**
 * Topic.updatedUser
 */
export type Topic$updatedUserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Topic.materials
 */
export type Topic$materialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  where?: Prisma.MaterialWhereInput
  orderBy?: Prisma.MaterialOrderByWithRelationInput | Prisma.MaterialOrderByWithRelationInput[]
  cursor?: Prisma.MaterialWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MaterialScalarFieldEnum | Prisma.MaterialScalarFieldEnum[]
}

/**
 * Topic.assignment
 */
export type Topic$assignmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment
   */
  select?: Prisma.AssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment
   */
  omit?: Prisma.AssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignmentInclude<ExtArgs> | null
  where?: Prisma.AssignmentWhereInput
  orderBy?: Prisma.AssignmentOrderByWithRelationInput | Prisma.AssignmentOrderByWithRelationInput[]
  cursor?: Prisma.AssignmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssignmentScalarFieldEnum | Prisma.AssignmentScalarFieldEnum[]
}

/**
 * Topic without action
 */
export type TopicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Topic
   */
  select?: Prisma.TopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Topic
   */
  omit?: Prisma.TopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopicInclude<ExtArgs> | null
}
