services:
  lms-api:
    image: lms-api:latest
    container_name: lms-api
    ports:
      - ${PORT}:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - TZ=${TZ}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    networks:
      - lms-network
    # Tetap jalankan migrasi sebelum start
    command: sh -c "npx prisma migrate deploy && node dist/main"

networks:
  lms-network:
    external: true
